services:
  _defaults:
    tags: ['doctrine.fixture.orm']
    autowire: true

  Shopsys\FrameworkBundle\DataFixtures\:
   resource: '../../../DataFixtures/'
   exclude: '../../../DataFixtures/{**/Exception,Demo/ProductDataFixtureLoader.php,Demo/ProductParametersFixtureLoader.php}'
